version: 2
updates:
    - package-ecosystem: github-actions #! for github-actions
      directory: '.github'
      schedule:
          interval: daily
          time: '21:00'
    - package-ecosystem: npm #! enable for javascript & typescript
      directory: 'client'
      schedule:
          interval: daily
          time: '21:00'
      
